-- MySQL Script generated by MySQL Workbench
-- Thu Nov 30 03:22:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema almoxarifado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema almoxarifado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `almoxarifado` DEFAULT CHARACTER SET utf8 ;
USE `almoxarifado` ;

-- -----------------------------------------------------
-- Table `almoxarifado`.`estrutura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`estrutura` (
  `idestrutura` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idestrutura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`rua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`rua` (
  `id_rua` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_rua`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`armazem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`armazem` (
  `idarmazem` INT(11) NOT NULL AUTO_INCREMENT,
  `idestrutura` INT(11) NOT NULL,
  `idrua` INT(11) NOT NULL,
  PRIMARY KEY (`idarmazem`),
  INDEX `fk_armazem_estrutura1_idx` (`idestrutura` ASC),
  INDEX `fk_armazem_rua1_idx` (`idrua` ASC),
  CONSTRAINT `fk_armazem_estrutura1`
    FOREIGN KEY (`idestrutura`)
    REFERENCES `almoxarifado`.`estrutura` (`idestrutura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_armazem_rua1`
    FOREIGN KEY (`idrua`)
    REFERENCES `almoxarifado`.`rua` (`id_rua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`nota` (
  `idnota` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Cada nota pode ser fiscal ou não. De toda forma um documento que determina a origem do lote.',
  `path` VARCHAR(255) NOT NULL COMMENT 'O path é caminho do documento que foi digitalizado. O php fará o upload do arquivo e vem pro banco apenas o caminho do arquivo.\n\nACHOU RUIM RESOLVA COMIGO.',
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idnota`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`lote` (
  `idlote` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'O lote é um evento para recebimento de produto(s)',
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `idnota` INT(11) NOT NULL,
  PRIMARY KEY (`idlote`, `idnota`),
  INDEX `fk_lote_notafiscal1_idx` (`idnota` ASC),
  CONSTRAINT `fk_lote_notafiscal1`
    FOREIGN KEY (`idnota`)
    REFERENCES `almoxarifado`.`nota` (`idnota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`representante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`representante` (
  `idrepresentante` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrepresentante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`fornecedor` (
  `idfornecedor` INT(11) NOT NULL AUTO_INCREMENT,
  `empresa` VARCHAR(100) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `idrepresentante` INT(11) NOT NULL,
  PRIMARY KEY (`idfornecedor`),
  INDEX `fk_fornecedor_contato1_idx` (`idrepresentante` ASC),
  CONSTRAINT `fk_fornecedor_contato1`
    FOREIGN KEY (`idrepresentante`)
    REFERENCES `almoxarifado`.`representante` (`idrepresentante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`produto` (
  `idproduto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `marca` VARCHAR(50) NOT NULL,
  `perecivel` TINYINT(4) NOT NULL COMMENT 'Caso o produto seja um perecivel, o sistema deve obrigar o cadastro da data de validade na tabela entrada.\\nQuando ocorrer um data de validade, a saída precisa respeitar a regra FIFO.',
  `descartavel` TINYINT(4) NOT NULL,
  `validade` TINYINT(4) NULL DEFAULT NULL,
  `data_criacao` DATETIME NOT NULL,
  `idarmazem` INT(11) NOT NULL,
  `idfornecedor` INT(11) NOT NULL,
  `idcategoria` INT(11) NOT NULL,
  `idcaixa` INT(11) NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_armazem1_idx` (`idarmazem` ASC),
  INDEX `fk_produto_fornecedor1_idx` (`idfornecedor` ASC),
  INDEX `fk_produto_categoria1_idx` (`idcategoria` ASC),
  INDEX `fk_produto_produto1_idx` (`idcaixa` ASC),
  CONSTRAINT `fk_produto_armazem1`
    FOREIGN KEY (`idarmazem`)
    REFERENCES `almoxarifado`.`armazem` (`idarmazem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `almoxarifado`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_fornecedor1`
    FOREIGN KEY (`idfornecedor`)
    REFERENCES `almoxarifado`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_produto1`
    FOREIGN KEY (`idcaixa`)
    REFERENCES `almoxarifado`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`entrada` (
  `idlote` INT(11) NOT NULL AUTO_INCREMENT,
  `idproduto` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `validade` DATETIME NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idlote`, `idproduto`),
  INDEX `fk_lote_has_produto_produto1_idx` (`idproduto` ASC),
  INDEX `fk_lote_has_produto_lote1_idx` (`idlote` ASC),
  CONSTRAINT `fk_lote_has_produto_lote1`
    FOREIGN KEY (`idlote`)
    REFERENCES `almoxarifado`.`lote` (`idlote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lote_has_produto_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `almoxarifado`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`solicitante` (
  `idsolicitante` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idsolicitante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`solicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`solicitacao` (
  `idemprestimo` INT(11) NOT NULL AUTO_INCREMENT,
  `idsolicitante` INT(11) NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idemprestimo`),
  INDEX `fk_emprestimo_solicitante1_idx` (`idsolicitante` ASC),
  CONSTRAINT `fk_emprestimo_solicitante1`
    FOREIGN KEY (`idsolicitante`)
    REFERENCES `almoxarifado`.`solicitante` (`idsolicitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`emprestimo` (
  `idemprestimo` INT(11) NOT NULL AUTO_INCREMENT,
  `idlote` INT(11) NOT NULL,
  `idproduto` INT(11) NOT NULL,
  `idsolicitacao` INT(11) NOT NULL,
  PRIMARY KEY (`idemprestimo`, `idlote`, `idproduto`, `idsolicitacao`),
  INDEX `fk_solicitacao_entrada1_idx` (`idlote` ASC, `idproduto` ASC) ,
  INDEX `fk_solicitacao_solicitacao1_idx` (`idsolicitacao` ASC),
  CONSTRAINT `fk_solicitacao_entrada1`
    FOREIGN KEY (`idlote` , `idproduto`)
    REFERENCES `almoxarifado`.`entrada` (`idlote` , `idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_solicitacao1`
    FOREIGN KEY (`idsolicitacao`)
    REFERENCES `almoxarifado`.`solicitacao` (`idsolicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`saida` (
  `idsaida` INT(11) NOT NULL AUTO_INCREMENT,
  `data_saida` DATETIME NOT NULL,
  `idlote` INT(11) NOT NULL,
  `id_produto` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `idemprestimo` INT(11) NOT NULL,
  PRIMARY KEY (`idsaida`, `id_produto`, `idlote`),
  INDEX `fk_registro_entrada1_idx` (`idlote` ASC, `id_produto` ASC),
  INDEX `fk_saida_emprestimo1_idx` (`idemprestimo` ASC),
  CONSTRAINT `fk_registro_entrada1`
    FOREIGN KEY (`idlote` , `id_produto`)
    REFERENCES `almoxarifado`.`entrada` (`idlote` , `idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saida_emprestimo1`
    FOREIGN KEY (`idemprestimo`)
    REFERENCES `almoxarifado`.`emprestimo` (`idemprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `almoxarifado`.`sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`sessao` (
  `id_sessao` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idrua` INT(11) NOT NULL,
  PRIMARY KEY (`id_sessao`, `idrua`),
  INDEX `fk_sessao_rua_idx` (`idrua` ASC),
  CONSTRAINT `fk_sessao_rua`
    FOREIGN KEY (`idrua`)
    REFERENCES `almoxarifado`.`rua` (`id_rua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
